format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$package\
$cmd_duration\
$line_break\
$status\
$character"""

palette = "sigma"

[palettes.sigma]
black = "#1A1A1A"
white = "#D4D8C0"
green = "#44B273"
red = "#D06070"
purple = "#A285EA"
blue = "#569CD6"
yellow = "#FFEE99"
cyan = "#33998A"


# [hostname]
# ssh_symbol = " "

# sigma theme settings
# # ➜    󰁕      󱦰
# [character]
# success_symbol = "[](bold cyan)"
# error_symbol = "[](bold red)"
#
# [directory]
# style = "bold blue"
# # read_only = " 󰌾"
# end sigma theme settings

[character]
# Note the use of Catppuccin color 'maroon'
# success_symbol = "[❯](green)"
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[directory]
truncation_length = 4
# Catppuccin 'lavender'
# style = "bold lavender"
style = "bold blue"

[git_branch]
format = "[$symbol](red)[$branch(:$remote_branch)](bold red) "
symbol = " "
# symbol = " "

[git_status]
style = "red"

[ruby]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[golang]
format = "[$symbol](bold blue)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

# [c]
# symbol = " "

[lua]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[python]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[rust]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[haskell]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[package]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = "󰏗 "

[nodejs]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
symbol = " "
detect_extensions = []
# disabled = true

[docker_context]
format = "[$symbol]($style)"
# symbol = "󰡨 "

# [aws]
# symbol = "  "

[memory_usage]
symbol = "󰍛 "

[jobs]
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
